[licenses]
allow = []
allow-osi-fsf-free = "both"
exceptions = [
    { allow = ["AGPL-3.0"], name = "quack" },
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]

[bans]
skip = [
    { name = "gloo-utils", version = "0.1" },
    { name = "hashbrown", version = "0.12" },
    { name = "indexmap", version = "1" },
    { name = "itertools", version = "0.10" },
    { name = "socket2", version = "0.4" },
]
