name: Deploy
on:
  push:
    branches: [main]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: deploy
  cancel-in-progress: false
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Setup Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm
      - name: Install binaryen
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends binaryen
      - name: Install cargo-binstall
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall
      - name: Install wazzup
        run: cargo binstall --no-confirm wazzup
      - name: Install tailwindcss
        run: pnpm install
      - name: Setup pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Build project
        run: wazzup build --release --base-url /quack
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist
  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
